language: node_js
node_js:
- node
- '7'
script: npm test
notifications:
  slack: agilesoftwarecourse:04DMpZE4tYwq9F5m4sWvWXaZ
before_install:
- openssl aes-256-cbc -K $encrypted_e8d31d247bc0_key -iv $encrypted_e8d31d247bc0_iv
  -in deploy_key.pem.enc -out deploy_key.pem -d
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 deploy_key.pem
- ssh-add deploy_key.pem
- git remote add deploy https://github.com/benjenkinsv95/agile-connors
- git push deploy
